In [1]:
import numpy as np

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [4]:
num = np.array([1,23,121,4,56,8,90,45])

In [5]:
type(num)

numpy.ndarray

In [6]:
num.dtype

dtype('int64')

In [7]:
num1 = num.astype(dtype=np.int16)

In [8]:
num1

array([  1,  23, 121,   4,  56,   8,  90,  45], dtype=int16)

In [9]:
num

array([  1,  23, 121,   4,  56,   8,  90,  45])

In [10]:
(num > 32)[:-1]

array([False, False,  True, False,  True, False,  True])

In [11]:
num2 = num[num>32]

In [12]:
num2

array([121,  56,  90,  45])

#### Matrix

In [13]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [14]:
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
mat.shape


(4, 3)

In [20]:
print(mat[0][1])

2
